from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlparse
from urllib.request import Request, urlopen
import json

from chromapress.services.ai_catalog import provider_by_id


@dataclass(frozen=True)
class AiRequest:
    provider: str
    endpoint: str
    api_key: str
    model: str
    prompt: str
    toolchain: str
    target_context: dict


def _validated_endpoint(req: AiRequest) -> str:
    provider = provider_by_id(req.provider)
    if provider.id == "openai":
        return "https://api.openai.com/v1"
    endpoint = req.endpoint.strip().rstrip("/")
    if provider.requires_endpoint and not endpoint:
        raise ValueError(f"{provider.label} requires an endpoint configured in Settings → Advanced")
    parsed = urlparse(endpoint)
    if parsed.scheme not in {"https", "http"} or not parsed.netloc:
        raise ValueError("AI endpoint must be a valid HTTP(S) URL")
    if parsed.scheme == "http":
        host = (parsed.hostname or "").casefold()
        if provider.id != "local" or host not in {"localhost", "127.0.0.1", "::1"}:
            raise ValueError("Cleartext HTTP is allowed only for the Local model endpoint on loopback")
    return endpoint


def _system_prompt(req: AiRequest) -> str:
    context = json.dumps(req.target_context or {}, ensure_ascii=False, sort_keys=True)
    return (
        "You are the coding engine inside ChromaPress AI App Studio. Generate a normal inspectable source project for the requested Linux target. "
        "Return ONLY project files using exact separators: --- relative/path --- followed by file content. No prose outside files. "
        "The project MUST include chromapress-app.json with: name, version, entrypoint, packages (target OS package names), services, permissions, "
        "autostart, desktop_integration, security_implications, build {command, requires_network}, and test {command, requires_network}. "
        "Never embed the generation API credential, passwords, tokens, private keys, or runtime credentials. Use environment/secret-store placeholders where runtime secrets are required. "
        "Do not assume dependencies exist: declare them in chromapress-app.json. Do not request privileged services/permissions unless needed and explain them in security_implications. chromapress-app.json is an internal ChromaPress review manifest only and must never be required by the generated application at runtime or shipped as part of the deployable application. Do not add ChromaPress branding, “Generated by ChromaPress” text, telemetry identifiers, hidden metadata, shared ChromaPress runtime stubs, or other ChromaPress fingerprints to any deployable project file. "
        "Build/test commands are review plans and must not assume ChromaPress will execute untrusted code on the host. "
        f"Selected toolchain: {req.toolchain}. Target Linux context: {context}."
    )


def prepare_request(req: AiRequest) -> tuple[str, dict[str, str], bytes]:
    provider = provider_by_id(req.provider)
    if provider.requires_api_key and not req.api_key.strip():
        raise ValueError("Generation API key is required for the selected provider")
    if not req.model.strip():
        raise ValueError("Model is required")
    endpoint = _validated_endpoint(req)
    if not endpoint.endswith("/chat/completions"):
        endpoint += "/chat/completions"
    body = json.dumps({
        "model": req.model,
        "messages": [
            {"role": "system", "content": _system_prompt(req)},
            {"role": "user", "content": req.prompt},
        ],
    }).encode("utf-8")
    headers = {"Content-Type": "application/json", "User-Agent": "ChromaPress/1"}
    if req.api_key.strip():
        headers["Authorization"] = f"Bearer {req.api_key.strip()}"
    return endpoint, headers, body


def generate_code(req: AiRequest) -> str:
    endpoint, headers, body = prepare_request(req)
    request = Request(endpoint, data=body, headers=headers, method="POST")
    with urlopen(request, timeout=120) as response:
        raw = json.loads(response.read().decode("utf-8"))
    content = raw.get("choices", [{}])[0].get("message", {}).get("content", "")
    if not content:
        raise RuntimeError("AI provider returned no source project")
    return content
