from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src" / "chromapress"


def _manifest_project(app_body: str = "print('hello')\n") -> str:
    manifest = {
        "name": "Neutral Demo",
        "version": "1.0",
        "entrypoint": "app.py",
        "packages": [],
        "services": [],
        "permissions": [],
        "autostart": [],
        "desktop_integration": [],
        "security_implications": ["No network service"],
        "build": {"command": "python -m compileall .", "requires_network": False},
        "test": {"command": "python -m unittest", "requires_network": False},
    }
    return "--- chromapress-app.json ---\n" + json.dumps(manifest) + "\n--- app.py ---\n" + app_body


def _target_context() -> dict:
    return {
        "distribution": "Ubuntu",
        "version": "26.04",
        "architecture": "amd64",
        "desktop": "LXQt",
        "package_format": "deb",
        "package_manager": "apt/dpkg",
        "available_libraries": ["python3"],
        "installer_type": "Subiquity/Autoinstall",
        "source_sha256": "a" * 64,
        "scenario": "Desktop",
        "scenario_context": "",
    }


def test_final_license_is_standard_mit_with_disclaimer_and_author():
    text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    assert text.startswith("MIT License\n")
    assert "Copyright (c) 2026 Janus Rokkjær" in text
    assert "Permission is hereby granted, free of charge" in text
    assert 'THE SOFTWARE IS PROVIDED "AS IS"' in text
    assert "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE" in text
    assert "ChromaPress Proprietary License" not in text
    assert (SRC / "assets" / "CHROMAPRESS_LICENSE.txt").read_text(encoding="utf-8") == text
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert 'license = {text = "MIT"}' in pyproject


def test_final_version_remains_accepted_alpha72_baseline():
    assert 'version = "1.0.0a72"' in (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert '__version__ = "1.0.0a72"' in (SRC / "__init__.py").read_text(encoding="utf-8")


def test_components_is_real_page_not_placeholder():
    main = (SRC / "gui" / "main_window.py").read_text(encoding="utf-8")
    page = (SRC / "gui" / "components_page.py").read_text(encoding="utf-8")
    assert 'self.components = ComponentsPage()' in main
    assert 'PlaceholderPage("Components"' not in main
    assert "INSTALLED_INVENTORY=READY" in page
    assert "selected-image" in page or "target-image" in page


def test_ai_generation_key_is_session_only_and_not_persisted():
    settings = (SRC / "settings.py").read_text(encoding="utf-8")
    main = (SRC / "gui" / "main_window.py").read_text(encoding="utf-8")
    dialog = (SRC / "gui" / "settings_dialog.py").read_text(encoding="utf-8")
    assert "ai_api_key" in settings
    assert "session-only" in settings or "runtime-only" in settings
    assert "ai_api_key is deliberately NOT written to QSettings" in main
    persist_block = main[main.index("def _save_settings"):main.index("def open_about")]
    assert '"ai_api_key"' not in persist_block
    assert "QLineEdit.EchoMode.Password" in dialog
    assert "kept only for this ChromaPress session" in dialog


def test_ai_deployable_output_excludes_internal_manifest_and_has_no_fingerprint():
    from chromapress.services.part6 import review_generated_project, ai_app_payload, validate_ai_app_payload

    review = review_generated_project(_manifest_project())
    assert review["status"] == "PASS"
    payload = ai_app_payload(
        review,
        _target_context(),
        provider="openai",
        model="gpt-5.6-sol",
        toolchain="Auto",
        prompt="Build a neutral demo",
        human_review_acknowledged=True,
    )
    assert payload["internal_control_files"] == ["chromapress-app.json"]
    assert payload["internal_control_files_deployed"] is False
    assert payload["generated_output_fingerprint_policy"] == "neutral_no_chromapress_markers"
    assert payload["generated_output_telemetry"] is False
    assert payload["generated_output_shared_chromapress_runtime"] is False
    paths = [row["path"] for row in payload["deployable_project_files"]]
    assert paths == ["app.py"]
    serialized = json.dumps(payload["deployable_project_files"]).casefold()
    assert "chromapress" not in serialized
    assert validate_ai_app_payload(payload)[0]


def test_ai_review_blocks_automatic_chromapress_fingerprint():
    from chromapress.services.part6 import review_generated_project

    review = review_generated_project(_manifest_project("print('Generated by ChromaPress')\n"))
    assert review["status"] == "BLOCKED"
    assert any("fingerprint" in item.casefold() for item in review["errors"])


def test_ai_prompt_explicitly_forbids_branding_manifest_shipping_telemetry_and_runtime_stub():
    source = (SRC / "services" / "ai.py").read_text(encoding="utf-8").casefold()
    assert "internal chromapress review manifest only" in source
    assert "must never be required by the generated application at runtime or shipped" in source
    assert "do not add chromapress branding" in source
    assert "telemetry identifiers" in source
    assert "shared chromapress runtime stubs" in source


def test_about_icon_mit_and_share_button_gui(monkeypatch):
    pytest.importorskip("PySide6")
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

    from PySide6.QtWidgets import QApplication, QMessageBox, QPushButton
    from chromapress.gui.about_dialog import (
        AboutDialog,
        chromapress_icon,
        license_text,
        share_text,
    )
    from chromapress.i18n import set_language

    app = QApplication.instance() or QApplication([])

    assert not chromapress_icon().isNull()

    # The authoritative MIT license remains the original English license text.
    assert "MIT License" in license_text()
    assert "Permission is hereby granted, free of charge" in license_text()

    monkeypatch.setattr(
        QMessageBox,
        "information",
        lambda *args, **kwargs: None,
    )

    # English remains a supported alternate language.
    set_language("en")
    english_message = share_text()
    assert "free and open-source" in english_message
    assert "share the official release" in english_message

    english_dialog = AboutDialog()
    english_button = english_dialog.findChild(
        QPushButton,
        "shareChromaPressButton",
    )
    assert english_button is not None
    assert english_button.text() == "Share ChromaPress"
    english_button.click()
    assert QApplication.clipboard().text() == english_message
    english_dialog.close()

    # Danish is the ChromaPress default/product language.
    set_language("da")
    danish_message = share_text()
    assert "gratis open source" in danish_message

    danish_dialog = AboutDialog()
    danish_button = danish_dialog.findChild(
        QPushButton,
        "shareChromaPressButton",
    )
    assert danish_button is not None
    assert danish_button.text() == "Del ChromaPress"
    danish_button.click()
    assert QApplication.clipboard().text() == danish_message
    danish_dialog.close()

    # Leave global language state at the product default for following tests.
    set_language("da")

def test_main_window_has_full_v1_navigation_and_actual_version_label():
    main = (SRC / "gui" / "main_window.py").read_text(encoding="utf-8")
    for label in (
        "Source", "Overview", "Applications", "Components", "Files", "System",
        "Boot & Hardware", "Installer", "Desktop", "AI App Studio", "Changes", "Build & Verify",
    ):
        assert f'"{label}"' in main
    about = (SRC / "gui" / "about_dialog.py").read_text(encoding="utf-8")
    assert "Version {__version__}" in about
    assert "QLabel(__version__)" not in main
    assert "v1 alpha 37" not in main


def test_release_sources_do_not_reintroduce_proprietary_license_markers():
    paths = [ROOT / "LICENSE", ROOT / "pyproject.toml"]
    paths.extend(p for p in SRC.rglob("*") if p.is_file() and p.suffix in {".py", ".txt", ".svg"})
    bad = []
    for path in paths:
        text = path.read_text(encoding="utf-8", errors="ignore")
        if "ChromaPress Proprietary License" in text or "All rights reserved" in text:
            bad.append(str(path.relative_to(ROOT)))
    assert bad == []
